StasTserk/foundry-burningwheel

.circleci/config.yml
.gitignore
gulpfile.js

Adds CircleCI config file to the project

Add .circleci/config.yml

---

.circleci/config.yml
gulpfile.js
package-lock.json
package.json
system.json

- Add gulp task to update version tags locally
- Add circleCI workflow for automated releases

CircleCI workflow changes for automated releases

---

module/actor-sheet.ts
module/actor.ts
module/burningwheel.ts
module/item.ts
module/items/belief-sheet.ts
module/items/instinct.ts
module/items/trait-sheet.ts
module/items/trait.ts
styles/character/character.scss
template.yml
templates/character-sheet.html
templates/items/trait.html
tsconfig.json

Initial implementation for the BITS of a character including beliefs, instincts and traits.

Character Bits

---

module/actor.ts
module/burningwheel.ts
module/bwactor-sheet.ts
module/character-sheet.ts
module/templates.ts
styles/character/character.scss
template.yml
templates/character-sheet.html
templates/parts/rollable-item.html
templates/parts/stat.html
tslint.json

Adds stats and attributes section to the character sheet

Character Stats

---

module/actor.ts
module/burningwheel.ts
module/bwactor-sheet.ts
module/character-sheet.ts
module/helpers.ts
module/item.ts
module/items/skill-sheet.ts
module/items/skill.ts
module/templates.ts
styles/burningwheel.scss
styles/character/character.scss
styles/dialog.scss
styles/roll.scss
template.yml
templates/character-sheet.html
templates/chat/roll-dialog.html
templates/chat/roll-message.html
templates/items/skill.html
templates/parts/rollable-item.html
templates/parts/rollable-skill.html

Adds skills to character sheet
Hooks up test tracking
Adds ability to edit items - skills and traits
Improvements to the roll popup and roll chat message templates
Minor styling improvements

Skills Implementation - Closes #13

---

module/actor.ts
module/character-sheet.ts
module/templates.ts
styles/burningwheel.scss
styles/character/character.scss
styles/character/ptgs.scss
system.json
template.yml
templates/character-sheet.html
templates/chat/roll-dialog.html
templates/chat/roll-message.html
templates/parts/ptgs.html
templates/parts/rollable-skill.html

- Adds the PTGS section
- Adds wound severity logic
- Adds wound logic with respect to rolls
Resolves #12

Add PTGS Section to the sheet

---

module/actor.ts
module/character-sheet.ts
module/items/skill.ts
module/templates.ts
styles/burningwheel.scss
styles/character/character.scss
styles/character/learning.scss
styles/items/skill.scss
styles/mixins.scss
template.yml
templates/character-sheet.html
templates/items/skill.html
templates/parts/learning.html
templates/parts/rollable-item.html
templates/parts/rollable-skill.html

Adds section to track learning new skills and training
Resolves #10

Add Training Section

---

module/burningwheel.ts
module/character-sheet.ts
module/item.ts
module/items/relationship-sheet.ts
module/items/relationship.ts
module/templates.ts
styles/burningwheel.scss
styles/character/character.scss
styles/character/learning.scss
styles/items/relationship.scss
styles/mixins.scss
template.yml
templates/character-sheet.html
templates/items/relationship.html
templates/parts/learning.html
templates/parts/relationships.html
templates/parts/rollable-item.html
templates/parts/rollable-skill.html

Adds relationship tracking to the game.
Refactors disabling progress ticks via the helper rather than with pure css
Resolves #7

Relationships

---

styles/burningwheel.scss
template.yml
templates/character-sheet.html

Add basic inputs to notes/spells section
No spell item type yet.
Resolves #9

Add spells/misc section

---

module/actor.ts
module/character-sheet.ts
module/items/skill.ts
module/rolls.ts
package-lock.json
styles/burningwheel.scss
styles/character/character.scss
styles/chat/dialog.scss
templates/character-sheet.html
templates/chat/roll-dialog.html
templates/chat/roll-message.html
templates/chat/skill-dialog.html
templates/parts/learning.html
templates/parts/rollable-item.html
templates/parts/rollable-skill.html

Refactors roll logic to a separate module.
Refactors different roll types to use separate code paths
Add FoRKs to skill rolls
Resolves #23

Roll rework 23

---

module/actor.ts
module/burningwheel.ts
module/bwactor-sheet.ts
module/character-sheet.ts
module/helpers.ts
module/items/skill.ts
module/rolls.ts
styles/character/character.scss
template.yml
templates/character-sheet.html
templates/parts/rollable-item.html
templates/parts/rollable-skill.html
tsconfig.json

Add a number of automatic tracking options to tests.
- Stats, Attributes and Skills property track tests.
- Skills being learned track only routine tests towards advancement
- Skills being learned shift more difficult tests to their root stats
Resolves #11 - Automate Skill Rolls

Test Automation

---

module/actor.ts
module/character-sheet.ts
module/helpers.ts
module/items/meleeWeapon.ts
module/items/rangedWeapon.ts
module/items/skill.ts
module/rolls.ts
styles/character/character.scss
styles/character/ptgs.scss
template.yml
templates/chat/shrug-dialog.html
templates/chat/skill-dialog.html
templates/parts/ptgs.html

See linked issue for details...
Resolves #21 - Add better wound handling

Improved Wound Handling

---

module/actor.ts
module/burningwheel.ts
module/chat.ts
module/helpers.ts
module/items/skill.ts
module/rolls.ts
module/rolls/rerollFate.ts
module/rolls/rollAttribute.ts
module/rolls/rollCircles.ts
module/rolls/rollLearning.ts
module/rolls/rollPtgs.ts
module/rolls/rollSkill.ts
module/rolls/rollStat.ts
styles/character/character.scss
styles/chat/roll.scss
template.yml
templates/chat/fate-reroll-message.html
templates/chat/roll-message.html
templates/items/skill.html
templates/parts/rollable-item.html

Adds a number of roll improvement
- Shade support
- Fate reroll support
- Open ended abilities and skills
- Styling improvements on chat messages
Resolves #36 - Improve Roll Support

Roll update 36

---

gulpfile.js
module/actor.ts
module/burningwheel.ts
module/character-sheet.ts
module/items/armor.ts
module/rolls.ts
module/rolls/rollAttribute.ts
module/rolls/rollCircles.ts
module/rolls/rollLearning.ts
module/rolls/rollSkill.ts
module/rolls/rollStat.ts
styles/burningwheel.scss
styles/character/weapons.scss
styles/items/armor.scss
template.yml
templates/character-sheet.html
templates/chat/circles-dialog.html
templates/chat/resources-dialog.html
templates/chat/roll-dialog.html
templates/chat/shrug-dialog.html
templates/chat/skill-dialog.html
templates/items/armor.html

Adds support for armor and clumsy weight.
- Adds roll modifier system that all die rolls take into account
- Adds automatic clumsy weight penalty based on armor being worn
- Adds untrained armor penalties depending on armor weight
- Modifies armor data structure to support penalties based on armor location
Resolves #27

Autmoate Clumsy Weight

---

module/actor.ts
module/character-sheet.ts
module/helpers.ts
module/items/armor.ts
styles/items/armor.scss
template.yml
templates/items/armor.html
templates/parts/armor.html

Resolves #53 - Rework Armor
Changes armor to be possible to condense to a single item. Separate damage sections, and penalty sections for each item.

Armor Rework

---

package-lock.json

Updates package.json with a number of newer dependencies after upgrading node and npm to latest

Updates package-lock.json post Node/Npm update

---

module/actor.ts
module/burningwheel.ts
module/character-sheet.ts
module/helpers.ts
module/items/item.ts
module/items/trait.ts
module/rolls.ts
module/rolls/rerollFate.ts
module/rolls/rollAttribute.ts
module/rolls/rollCircles.ts
module/rolls/rollLearning.ts
module/rolls/rollPtgs.ts
module/rolls/rollResources.ts
module/rolls/rollSkill.ts
module/rolls/rollStat.ts
styles/burningwheel.scss
styles/items/trait.scss
template.yml
templates/items/trait.html

- Modifies trait UI to allow support for a number of ways that traits can affect rolls.
- Adds ability for traits to modify die amounts and obstacles in a roll
- Adds ability for traits to attach reputations and affiliations when added to a character.
Bonus add:
- Adds support for Dice So Nice module
Resolves #26 - Traits Support

Automated Traits

---

module/actor.ts
module/chat.ts
module/items/trait.ts
module/rolls.ts
module/rolls/rerollCallon.ts
module/rolls/rerollFate.ts
module/rolls/rollAttribute.ts
module/rolls/rollCircles.ts
module/rolls/rollLearning.ts
module/rolls/rollPtgs.ts
module/rolls/rollResources.ts
module/rolls/rollSkill.ts
module/rolls/rollStat.ts
styles/chat/roll.scss
styles/items/trait.scss
template.yml
templates/chat/reroll-message.html
templates/chat/roll-message.html
templates/items/trait.html

- Adds new field to traits relating to which stats they target.
- Adds call on reroll buttons
- Adds custom callon reroll behaviour.
Resolves #48

Add roll support for call-on traits

---

module/character-sheet.ts
styles/character/weapons.scss
templates/character-sheet.html
templates/items/skill.html

Add training skill checkbox to skill sheet
Add separate training skill section.
Resolves #49

Add training skills

---

templates/character-sheet.html
templates/parts/ptgs.html

Fix a number of issues where multiple character sheets open at the
same time would end up with duplicate input field IDs being generated
causing changes to one sheet to be performed on a different one.
Resolves #63 - Multiple sheet issues

Fix a number of duplicate ID issues

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
module/character-sheet.ts
module/items/relationship.ts
module/rolls/rollCircles.ts
styles/burningwheel.scss
styles/character/character.scss
styles/character/ptgs.scss
styles/character/relationships.scss
styles/items/skill.scss
styles/mixins.scss
system.json
templates/character-sheet.html
templates/items/armor.html
templates/items/meleeWeapon.html
templates/items/posession.html
templates/items/property.html
templates/items/rangedWeapon.html
templates/items/relationship.html
templates/items/reputation.html
templates/items/skill.html
templates/items/trait.html

A number of bug fixes and style changes as per the linked issue
Resolves #57 - Pre-cleanup pass

Pre 0.2.0 Cleanup

---

module/actor.ts
module/burningwheel.ts
module/character-sheet.ts
module/constants.ts
module/helpers.ts
module/items/item.ts
module/items/skill.ts
styles/character/learning.scss
styles/mixins.scss
templates/character-sheet.html
templates/chat/new-skill-dialog.html
templates/items/skill.html

Adds a "Learn new skill" button to the learning section which allows a user to either define a new skill to be learned or to pick one from an existing list. Adds the skill to the character sheet afterwards.
Resolves #51

Add Learn New Skill Button

---

styles/character/character.scss
templates/character-sheet.html

The character sheet is missing the stride and mounted stride fields
Resolves #71

Missing Stride Field

---

module/actor.ts
module/items/skill.ts
module/rolls/rollSkill.ts
module/rolls/rolls.ts
template.yml
templates/chat/roll-message.html
templates/chat/skill-dialog.html
templates/items/skill.html

Adds the concept of a "wild fork" where a die explodes on a 6 or a 1
with 1's potentially taking away successes from the total roll. The
main example of this behaviour is the Astrology skill, however others
with the behaviour may now be defined.
Closes #47

BW-47 Add the concept of a "wild fork"

---

module/actor.ts
module/helpers.ts
module/rolls/rollLearning.ts
module/rolls/rolls.ts
styles/character/weapons.scss
template.yml
templates/character-sheet.html
templates/parts/weapons.html

- Adds logic for rolling weapon attacks.
- Reorders the weapon section.
- Adds roll support for rolling skills as part of a weapon attack.
Resolves #46 - Combat roll macros

Add weapon roll buttons

---

module/actor.ts
module/character-sheet.ts
module/constants.ts
module/helpers.ts
module/items/item.ts
module/items/sheets/melee-sheet.ts
module/items/sheets/spell-sheet.ts
module/items/spell.ts
module/rolls/rolls.ts
module/templates.ts
styles/burningwheel.scss
styles/character/character.scss
styles/character/ptgs.scss
styles/items/armor.scss
styles/items/spell.scss
styles/items/trait.scss
styles/mixins.scss
template.yml
templates/character-sheet.html
templates/items/rangedWeapon.html
templates/items/spell.html
templates/parts/spell.html

Adds spells as an item type.
Adds character sheet section for spells.
Adds support for rolling spells from the spell entry.
Closes #68 - Add spell item type

Add spell item

---

module/helpers.ts
module/items/armor.ts
module/rolls/rerollFate.ts
module/rolls/rollArmor.ts
module/rolls/rollCircles.ts
module/rolls/rollLearning.ts
module/rolls/rolls.ts
styles/character/weapons.scss
styles/chat/roll.scss
templates/chat/armor-dialog.html
templates/chat/roll-message.html
templates/parts/armor.html

Resolves #89 - Add armor roll action
Allows armor dice to be rolled
Adds ability to track armor damage
Adds section to chat messages that broadcast custom info.

Armor Rolls

---

module/burningwheel.ts
module/character-sheet.ts
module/helpers.ts
module/items/skill.ts
styles/chat/dialog.scss
styles/items/skill.scss
template.yml
templates/character-sheet.html
templates/chat/new-skill-dialog.html
templates/items/affiliation.html
templates/items/reputation.html
templates/items/skill.html
templates/items/spell.html
templates/items/trait.html
templates/parts/relationships.html
templates/parts/rollable-item.html
templates/parts/rollable-skill.html

Resolves #81 - Improve Skill Learning Dialog

Improve Skill Learning Dialog

---

module/actor.ts
module/constants.ts
module/items/armor.ts
module/items/meleeWeapon.ts
module/items/rangedWeapon.ts
module/migration.ts
module/rolls/rerollFate.ts
module/rolls/rollArmor.ts
system.json
template.yml
templates/character-sheet.html
templates/items/armor.html
templates/items/meleeWeapon.html
templates/items/rangedWeapon.html
templates/parts/armor.html
templates/parts/ptgs.html
templates/parts/weapons.html

Few Minor Changes before 0.2.2 Release

---

gulpfile.js
module/character-sheet.ts
module/dialogs/burner-data-helpers.ts
module/dialogs/character-burner.ts
module/items/trait.ts
package-lock.json
package.json
styles/dialog/character-burner.scss
system.json
templates/dialogs/character-burner.html
templates/items/spell.html
templates/items/trait.html
tsconfig.json

Character burner name inputs now are select2 dropdowns.
Adds burner popup for new characters.
Adds loading dialog for when the character burner is being opened.
Closes #100 - Make character burner name lookup case insensitive - Instead it invalidates the issue.

Changes Character Burner Name Inputs to Select2

---

module/actor.ts
module/rolls/rollArmor.ts
module/rolls/rollAttribute.ts
module/rolls/rollCircles.ts
module/rolls/rollLearning.ts
module/rolls/rollPtgs.ts
module/rolls/rollResources.ts
module/rolls/rollSkill.ts
module/rolls/rollSpell.ts
module/rolls/rollSpellTax.ts
module/rolls/rollStat.ts
module/rolls/rollWeapon.ts
module/rolls/rolls.ts
styles/burningwheel.scss
styles/character/spells.scss
template.yml
templates/character-sheet.hbs
templates/parts/rollable-item.hbs

Adds spell sustain section, adds tax tests to spellcasting
Resolves #90

Spells and tax

---

module/burningwheel.ts
module/bwactor.ts
module/migration.ts

Fix a number of multi-user errors

---

README.md
module/burningwheel.ts
module/dialogs/duel-of-wits.ts
module/settings.ts
styles/burningwheel.scss
styles/dialog/duel-of-wits.scss
system.json
templates/dialogs/duel-of-wits.hbs
templates/npc-sheet.hbs

Resolves #120 - Duel of Wits dialog

Duel of Wits

---

module/rolls/npcSkillRoll.ts
module/rolls/npcStatRoll.ts
module/rolls/rollAttribute.ts
module/rolls/rollCircles.ts
module/rolls/rollLearning.ts
module/rolls/rollPtgs.ts
module/rolls/rollResources.ts
module/rolls/rollSkill.ts
module/rolls/rollSpellTax.ts
module/rolls/rollStat.ts
module/rolls/rolls.ts
templates/chat/roll-dialog.hbs

Refactor Rolls

---

module/character-sheet.ts
module/dialogs/importItemDialog.ts
module/items/spell.ts
styles/character/character.scss
styles/chat/dialog.scss
templates/character-sheet.hbs

Bw 126 130 add item buttons

---

module/bwactor-sheet.ts
module/character-sheet.ts
module/npc-sheet.ts
module/rolls/rollArmor.ts
module/rolls/rolls.ts
templates/npc-sheet.hbs

Resolves #121 
Also adds a number of extra "add" buttons to the npc sheet for adding new items, weapons, etc.

Bw 121 npc armor

---

module/dialogs/character-burner.ts
module/items/item.ts
module/items/property.ts
module/items/skill.ts
module/items/trait.ts
templates/items/skill.hbs

Hide skill options

---

module/bwactor.ts
module/dialogs/importItemDialog.ts

Resovles #138 
There still remains a lingering issue with importing items that then import other items. Unclear on the exact fix yet.

Ensure imported items are added in bulk

---

module/constants.ts
module/dialogs/duel-of-wits.ts
module/helpers.ts
module/items/meleeWeapon.ts
module/items/sheets/melee-sheet.ts
module/migration.ts
module/rolls/npcSkillRoll.ts
module/rolls/rollWeapon.ts
styles/burningwheel.scss
styles/items/weapon.scss
system.json
template.yml
templates/items/meleeWeapon.hbs
templates/npc-sheet.hbs
templates/parts/weapons.hbs

Weapon Multi Attacks

---

module/bwactor-sheet.ts
module/character-sheet.ts
module/items/meleeWeapon.ts
module/items/rangedWeapon.ts
module/items/sheets/melee-sheet.ts
module/items/spell.ts
module/npc-sheet.ts
package-lock.json
package.json

Updates typescript and a number of other libraries to version 4.
Fixes a number of compilation errors resultant from that.

Update to Typescript 4

---

module/character.ts

When a player's base stats change, that is now reflected in the number
of tests still needed in any given skill being learned that is based off
of that stat.
Resolves #37

Fix skill aptitude updating

---

module/burningwheel.ts
styles/burningwheel.scss
styles/character/character.scss
styles/npc/npc.scss
templates/character-sheet.hbs
templates/items/armor.hbs
templates/items/meleeWeapon.hbs
templates/items/possession.hbs
templates/items/property.hbs
templates/items/rangedWeapon.hbs
templates/items/spell.hbs
templates/items/trait.hbs
templates/npc-sheet.hbs
templates/parts/armor.hbs
templates/parts/character-settings.hbs

0.4.1 Style Pass

---

module/rolls/rollLearning.ts
module/rolls/rollSkill.ts
module/rolls/rolls.ts
styles/chat/roll.scss

Toolkit Fixes

---

module/dialogs/duel-of-wits.ts

Add feint and incite DoW actions

---

module/burningwheel.ts
module/dialogs/character-burner.ts
module/dialogs/importItemDialog.ts
module/rolls/npcSkillRoll.ts
module/rolls/npcStatRoll.ts
module/rolls/rollSkill.ts
styles/character/character.scss
template.yml

Resolves #165
Resolves #166
Resolves #170

Bw 165 166 170 bugfixes

---

styles/dialog/fight.scss
templates/dialogs/fight.hbs

Move buttons that allow an actor to roll their actions up to the area
where the actions themselves are displayed.
Resolves #163

Move fight roll buttons to volley area.

---

templates/items/rangedWeapon.hbs

Add range dice input to ranged weapon sheet

---

module/burningwheel.ts
module/character-sheet.ts
module/items/item.ts
module/items/spell.ts
module/rolls/rollSpell.ts
styles/character/character.scss
styles/character/spells.scss
styles/mixins.scss
system.json
template.yml
templates/character-sheet.hbs
templates/items/spell.hbs
templates/parts/spell.hbs

Resolves #149 #155 
Adds support for learning spells
Adds support for spells that scale off of half will instead of full will for damage.

Spells Imrovements

---

module/bwactor.ts
module/items/skill.ts
module/items/spell.ts
module/items/trait.ts
template.yml
templates/items/trait.hbs

Aptitude traits

---

module/bwactor.ts
module/dialogs/duel-of-wits.ts
module/rolls/npcSkillRoll.ts
module/rolls/npcStatRoll.ts
module/rolls/rollLearning.ts
module/rolls/rollSkill.ts
styles/dialog/duel-of-wits.scss
templates/dialogs/duel-of-wits.hbs

Duel of Wits roll button

---

module/burningwheel.ts

Fix an issue with spell learning dots

---

module/dialogs/fight.ts
module/rolls/fightRoll.ts
module/rolls/rollWeapon.ts

Improve fight dialog error handling

---

templates/dialogs/duel-of-wits.hbs

Fix broken placeholder image for DoW

---

.circleci/config.yml
module/character-sheet.ts
package-lock.json
styles/burningwheel.scss
styles/character/character.scss
styles/mixins.scss
templates/character-sheet.hbs
templates/dialogs/fight.hbs

Fixes a number of small UI issues
Resolves #196 - Pointer type improvements
Resolves #198 - Delete item conformation
Resolves #199 - Switch to not rendering (instead of setting display to `none`) for hidden character sheet sections.

Minor Usability Improvements

---

module/npc-sheet.ts
module/rolls/npcSkillRoll.ts
module/rolls/npcStatRoll.ts
module/rolls/rollLearning.ts
module/rolls/rolls.ts
templates/chat/roll-dialog.hbs
templates/dialogs/npc-roll-dialog.hbs
templates/npc-sheet.hbs

Resolves #190 
Allows NPCs to easily roll untrained skill checks defaulting to the correct stat usage behavior.

Unskilled Npc Rolls

---

gulpfile.js
styles/burningwheel.scss
styles/character/bits.scss
styles/items/item.scss
styles/items/skill.scss
templates/items/affiliation.hbs
templates/items/armor.hbs
templates/items/meleeWeapon.hbs
templates/items/possession.hbs
templates/items/property.hbs
templates/items/rangedWeapon.hbs
templates/items/relationship.hbs
templates/items/reputation.hbs
templates/items/skill.hbs
templates/items/spell.hbs
templates/items/trait.hbs

Resolves #209 - Skill item sheet resizing
Also makes this change for all other item sheets.
Resovles #208

Skill resizing

---

module/npc-sheet.ts
styles/npc/npc.scss
templates/npc-sheet.hbs
templates/parts/npc-skill.hbs

Indicate NPC skills are not rollable due to wounds

---

module/burningwheel.ts
module/character.ts
module/helpers.ts
module/items/meleeWeapon.ts
module/items/rangedWeapon.ts
module/npc.ts
module/rolls/rollAttribute.ts
styles/npc/npc.scss
system.json
template.yml
templates/npc-sheet.hbs
templates/parts/weapons.hbs

Resolves #169 
Resolves #219 
Resolves #220

Heroic effects

---

module/dialogs/rangeAndCover.ts

Enable clear and reset buttons in Range and Cover

---

module/burningwheel.ts
module/dialogs/difficultyDialog.ts
module/rolls/rolls.ts
module/settings.ts
styles/dialog/difficulty.scss
templates/dialogs/gm-difficulty.hbs

Adds a section to the GM obstacle dialog for setting up additional obstacle modifiers for things like environmental effects, etc.
Resolves #238

Global difficulty mods

---

module/dialogs/burnerDataHelpers.ts
module/rolls/rollWeapon.ts
module/rolls/rolls.ts

Bw 245 246 247 hotfix

---

module/dialogs/difficultyDialog.ts
module/migration/migration.ts
module/migration/task063.ts

Keypress tie-in for obstacle dialog.

---

module/macros/EditMacro.ts
module/macros/MeleeMacro.ts
module/macros/RangedMacro.ts
module/macros/SkillMacro.ts
module/macros/SpellMacro.ts

Add error checking to macros

---

module/actors/sheets/bwactor-sheet.ts
module/actors/sheets/character-sheet.ts
module/actors/sheets/npc-sheet.ts
module/helpers.ts
module/macros/Macro.ts
module/macros/StatMacro.ts
module/rolls/rollAttribute.ts
module/rolls/rollCircles.ts
module/rolls/rollResources.ts
templates/npc-sheet.hbs
templates/parts/npc-stat.hbs
templates/parts/rollable-item.hbs

Draggable stats

---

module/dialogs/importItemDialog.ts
templates/dialogs/new-item-dialog.hbs
templates/parts/npc-stat.hbs

Import item dialogs which can be opened through the character sheet now
support drag and drop functionality.
Resolves #252

Make import items draggable

---

module/actors/bwactor.ts
module/actors/sheets/character-sheet.ts
module/constants.ts
module/dialogs/burnerDataHelpers.ts
module/dialogs/importItemDialog.ts
templates/dialogs/character-burner.hbs

Default images

---

module/dialogs/burnerDataHelpers.ts
module/dialogs/characterBurner.ts
module/items/relationship.ts
system.json
template.yml
templates/items/relationship.hbs

Adds relationship influence to relationship sheet, other related changes.
Resolves #263

Relationship influence

---

module/dialogs/CharacterBurnerDialog.ts
styles/dialog/character-burner.scss

Burner viewing

---

module/actors/sheets/BWSettingSheet.ts
templates/parts/lifepath.hbs

Minor tweaks to setting sheet

---

module/actors/BWActor.ts
module/actors/sheets/BWCharacterSheet.ts
module/constants.ts
module/items/belief.ts
module/items/instinct.ts
module/items/item.ts
module/items/relationship.ts
module/items/sheets/belief-sheet.ts
module/items/sheets/instinct-sheet.ts
module/macros/Macro.ts
styles/burningwheel.scss
styles/character/bits.scss
styles/chat/roll.scss
styles/items/belief.scss
system.json
template.yml
templates/character-sheet.hbs
templates/chat/simple-broadcast.hbs
templates/items/belief.hbs
templates/items/instinct.hbs

Resolves #272 - Track artha spent pursuing beliefs.
Does not include automating Artha tracking as it is spent. I'm not certain as to the best way to insert this into the already complicated rolling mechanism.
Resolves #273 - Broadcast beliefs

Belief update

---

module/actors/BWCharacter.ts
module/burningwheel.ts
module/chat.ts
module/constants.ts
module/dialogs/DifficultyDialog.ts
module/helpers.ts
module/items/belief.ts
module/items/instinct.ts
module/items/item.ts
module/items/skill.ts
module/rolls/rollLearning.ts
module/rolls/rollSkill.ts
module/settings.ts
styles/dialog/difficulty.scss
templates/dialogs/gm-difficulty.hbs

Extended Tests

---

module/chat.ts
module/dialogs/DifficultyDialog.ts
module/items/trait.ts
module/templates.ts
styles/character/bits.scss
templates/character-sheet.hbs
templates/chat/simple-broadcast.hbs
templates/parts/trait.hbs

Trait Broadcast

---

module/dialogs/DifficultyDialog.ts
module/dialogs/FightDialog.ts
module/rolls/fightRoll.ts

Resolves #283 - Fight dialog not picking up additional penalty options
Resolves #281 - Non GMs adding to extended test dialog were not persisting it properly.

Modifier bugs

---

module/actors/sheets/BWSettingSheet.ts
module/burningwheel.ts
module/chat.ts
module/dialogs/DifficultyDialog.ts
module/dialogs/ModifierDialog.ts
module/dialogs/ModifierDialot.ts
module/dialogs/buildHelpDialog.ts
module/macros/Macro.ts
module/rolls/npcSkillRoll.ts
module/rolls/npcStatRoll.ts
module/rolls/rollAttribute.ts
module/rolls/rollCircles.ts
module/rolls/rollLearning.ts
module/rolls/rollPtgs.ts
module/rolls/rollResources.ts
module/rolls/rollSkill.ts
module/rolls/rollSpell.ts
module/rolls/rollSpellTax.ts
module/rolls/rollStat.ts
module/rolls/rolls.ts
styles/chat/dialog.scss
styles/dialog/difficulty.scss
templates/dialogs/gm-difficulty.hbs
templates/dialogs/help-dialog.hbs
templates/dialogs/mods-and-help.hbs
templates/dialogs/roll-dialog.hbs
tsconfig.json

Resolves #279 - Helping Automation
Incidentally Resolves #282

Helping Dice

---

module/dialogs/ModifierDialog.ts

Fix multiple help message broadcast issue

---

module/burningwheel.ts
module/dialogs/DifficultyDialog.ts
module/dialogs/ModifierDialog.ts
module/dialogs/index.ts

Resolves #290 - Incorrect socket listener registration was causing an issue with excessive database writes happening when the help or extended test dialogs were redrawn.
Includes some minor refactoring to dialog initialization

Multiple DB Write bug

---

module/actors/sheets/BWCharacterSheet.ts

Add filtering for training skills

---

module/items/skill.ts

Fix root calculation to ignore aptitude modifiers

---

module/decorators.ts
module/dialogs/DifficultyDialog.ts
module/dialogs/DuelOfWitsDialog.ts
module/dialogs/ExtendedTestDialog.ts
module/dialogs/FightDialog.ts
module/dialogs/ModifierDialog.ts
module/dialogs/RangeAndCoverDialog.ts
tsconfig.json

Adds some simple decorators for gm permission checks relating to persisting data.
Resolves #296

Decorators

---

module/actors/BWActor.ts
module/actors/BWCharacter.ts
module/actors/sheets/BWActorSheet.ts
module/actors/sheets/BWCharacterSheet.ts
module/actors/sheets/BWSettingSheet.ts
module/actors/sheets/NpcSheet.ts
system.json
templates/dialogs/help-dialog.hbs

Resolves #298
In addition contains a number of minor code improvements

Test with Foundry 0.7.9

---

module/actors/BWSetting.ts
module/actors/sheets/BWSettingSheet.ts
styles/setting.scss
templates/parts/lifepath.hbs
templates/setting-sheet.hbs

Adds improved drag and drop support for Setting actor types and the lifepaths contained therein.
Resolves #304

Setting and Lifepath sorting

---

module/actors/BWActor.ts
module/actors/BWCharacter.ts
module/actors/Npc.ts
module/dialogs/CharacterBurnerDialog.ts

Resolves #305
Includes some cleanup and fixes for embedded entity creation

Add some default actor settings

---

module/items/item.ts

Fix hasOwner flag getting unset during prepareData

---

templates/npc-sheet.hbs

Fix 0 Exp NPC skills display bug.

---

styles/dialog/duel-of-wits.scss
styles/dialog/fight.scss
styles/dialog/range-and-cover.scss
templates/dialogs/fight.hbs

Addendum to #319 to suit my personal preferences.

Fight overhaul

---

CONTRIBUTING.md

I went for the most meta first PR
Just fixing a minor spelling error.

Fix spelling error in contributor guidelines

---

.eslintrc.js
module/actors/sheets/BWSettingSheet.ts
module/dialogs/index.ts
module/items/sheets/lifepath-sheet.ts

Add rule banning console.log

---

module/actors/sheets/BWActorSheet.ts
module/actors/sheets/BWSettingSheet.ts
module/dialogs/CharacterBurnerDialog.ts
module/dialogs/DuelOfWitsDialog.ts
module/dialogs/FightDialog.ts
module/dialogs/RangeAndCoverDialog.ts
module/items/sheets/bwItemSheet.ts
styles/burningwheel.scss
styles/dialog/difficulty.scss

Standardize some styles between browsers

---

module/rolls/rolls.ts

Fixes an issue where the roll promise was being passed into DSN instead
of the roll object itself.
Also removed the delay after dice being rolled and the message appearing
since that can be configured as part of DSN itself.

Fix issue with DSN integration

---

module/actors/BWActor.ts

Fixes an issue introduce as part of #347 that caused item creation to
fail for new characters.
Resolves #349

Fix bug preventing default item creation

---

styles/character/character.scss
templates/character-tabbed-sheet.hbs
templates/parts/armor.hbs
templates/parts/learning.hbs
templates/parts/ptgs.hbs
templates/parts/relationships.hbs
templates/parts/rollable-item.hbs
templates/parts/rollable-skill.hbs
templates/parts/spell.hbs
templates/parts/weapons.hbs
templates/sections/spells.hbs

* Change tabs to be anchor tags.
* Explicitly set buttons on character sheet to be of type "button", 
to prevent unintended submit behaviour when pressing 'enter'

Character sheet submit behaviour hotfix

---

module/rolls/rollSpellTax.ts

Fix error on quick submit of tax roll dialog

---

templates/dialogs/duel-of-wits.hbs
templates/dialogs/fight.hbs
templates/dialogs/range-and-cover.hbs

Fix extend test dialog button types

---

module/items/skill.ts

Fixes an issue with tracking challenging tests

---

templates/sections/weapons-and-armor.hbs

Corrected Training skill data-id in weapons-and-armor.hbs
bugfix for issue  #370

Issue 370: fixed edit/delete bug on training skills

---

module/dialogs/CharacterBurnerDialog.ts
module/helpers.ts

- created escapeQuotes() function to escape both quotes and apostrophes
- used escapeQuotes() to fix bug when dropping items on the character burner
bugfix for issue #337

fixed quote bug on burner

---

module/actors/sheets/BWActorSheet.ts
styles/character/learning.scss
styles/character/relationships.scss
styles/npc/npc.scss
templates/character-sheet.hbs
templates/character-tabbed-sheet.hbs
templates/npc-sheet.hbs
templates/parts/learning.hbs
templates/parts/ptgs.hbs
templates/parts/relationships.hbs
templates/parts/rollable-item.hbs
templates/parts/rollable-skill.hbs
templates/parts/spell.hbs
templates/parts/trait.hbs
templates/parts/weapons.hbs
templates/sections/attributes.hbs
templates/sections/beliefs.hbs
templates/sections/gear.hbs
templates/sections/header.hbs
templates/sections/instincts.hbs
templates/sections/learning.hbs
templates/sections/misc.hbs
templates/sections/ptgs.hbs
templates/sections/skills.hbs
templates/sections/social.hbs
templates/sections/spells.hbs
templates/sections/stats.hbs
templates/sections/traits.hbs
templates/sections/weapons-and-armor.hbs

Bw 366 permission based rendering

---

module/actors/sheets/BWCharacterSheet.ts
module/constants.ts
module/dialogs/CharacterBurnerDialog.ts
module/items/skill.ts
module/migration/migration.ts
module/migration/task121.ts
styles/dialog/character-burner.scss
template.yml
templates/dialogs/character-burner.hbs
templates/items/skill.hbs

Bw 371 training skills

---

templates/dialogs/character-burner.hbs

Fixed the error mentioned in #383 

Correct Health Reminder in CB Worksheet

---

module/actors/BWActor.ts
module/actors/BWCharacter.ts
module/dialogs/DifficultyDialog.ts
module/dialogs/ModifierDialog.ts
module/rolls/rerollFate.ts
module/rolls/rerollTraitors.ts
module/rolls/rollAttribute.ts
module/rolls/rollCircles.ts
module/rolls/rollLearning.ts
module/rolls/rollPtgs.ts
module/rolls/rollSpellTax.ts
module/rolls/rollStat.ts
templates/character-sheet.hbs

Resolves #391 - Errors creating new actors
Resolves #392 - Errors on most non-item rolls

Bw 391 392 hotfixes

---

module/items/spell.ts

Fix an issue calculating spell weapon IMS

---

gulpfile.js
lang/en.yml
system.json
templates/sections/beliefs.hbs
templates/sections/header.hbs
templates/sections/instincts.hbs
templates/sections/traits.hbs

Starts basic localization framework for the system.
Resolves #406 
Resolves #407

Localization starter

---

lang/en.yml
templates/parts/rollable-item.hbs
templates/sections/stats.hbs

Adds localization to character Stats section
Resolves #409

Localize stats section

---

lang/en.yml
styles/character/character.scss
templates/sections/attributes.hbs

Adds localization to attributes section in character sheet.
Resolves #410

Localize attributes

---

lang/en.yml
templates/parts/spell.hbs
templates/sections/gear.hbs
templates/sections/misc.hbs
templates/sections/social.hbs
templates/sections/spells.hbs

Localizes all sections between relationships up to notes.
Resolves #411 
Resolves #412
Resolves #413 
Resolves #414

More character localization

---

lang/en.yml
templates/parts/ptgs.hbs
templates/sections/learning.hbs
templates/sections/ptgs.hbs
templates/sections/skills.hbs

Localize Skills, Learning, and PTGS sections of the sheet.
Resolves #415 
Resolves #416

Localize more character sheet sections

---

lang/en.yml
module/burningwheel.ts
templates/parts/armor.hbs
templates/parts/weapons.hbs
templates/sections/character-settings.hbs
templates/sections/footer.hbs
templates/sections/weapons-and-armor.hbs

Localizes weapons section of character sheet
Also localizes settings page and character sheet footer.
Resolves #417

Bw 417 localize weapons

---

module/actors/BWCharacter.ts

Fix issue with stat advancement

---

lang/en.yml
module/actors/BWCharacter.ts
module/dialogs/buildHelpDialog.ts
module/items/skill.ts
module/rolls/npcSkillRoll.ts
module/rolls/npcStatRoll.ts
module/rolls/rerollFate.ts
module/rolls/rerollTraitors.ts
module/rolls/rollArmor.ts
module/rolls/rollAttribute.ts
module/rolls/rollCircles.ts
module/rolls/rollLearning.ts
module/rolls/rollPtgs.ts
module/rolls/rollResources.ts
module/rolls/rollSkill.ts
module/rolls/rollSpell.ts
module/rolls/rollSpellTax.ts
module/rolls/rollStat.ts
module/rolls/rollWeapon.ts
module/rolls/rolls.ts
templates/chat/reroll-message.hbs
templates/chat/roll-message.hbs
templates/dialogs/help-dialog.hbs
templates/dialogs/roll-dialog.hbs
templates/parts/spell.hbs
templates/sections/spells.hbs
templates/sections/weapons-and-armor.hbs

Lots of roll related localization
Resolves #432
Resolves #421
Resolves #422 
Resolves #428

Bw 432 421 localize rolls

---

lang/en.yml
module/burningwheel.ts
templates/dialogs/gm-difficulty.hbs
templates/dialogs/mods-and-help.hbs

Localize GM difficulty dialog

---

module/dialogs/DifficultyDialog.ts

Fix issue with deferred tests

---

module/constants.ts
module/items/sheets/spell-sheet.ts
module/items/spell.ts

Add missile weapon length

---

templates/items/affiliation.hbs

Localize affiliation item sheet

---

lang/en.yml
templates/items/belief.hbs

Localize belief item sheet

---

templates/items/instinct.hbs

Localize instinct item sheet

---

lang/en.yml
module/constants.ts
templates/items/armor.hbs

Localize armor item sheet

---

lang/en.yml
templates/items/possession.hbs

Localize possession sheet

---

lang/en.yml
module/constants.ts
templates/items/meleeWeapon.hbs

Localize melee weapon sheet

---

lang/en.yml
templates/items/relationship.hbs

Localize relationship sheet

---

lang/en.yml
templates/items/reputation.hbs

Localize reputation sheet

---

lang/en.yml
module/constants.ts
templates/items/skill.hbs
templates/parts/spell.hbs
templates/parts/weapons.hbs
templates/sections/learning.hbs
templates/sections/skills.hbs

Localize skill sheet

---

lang/en.yml
templates/items/lifepath.hbs

WIP on #437
- Static wording localized
- **Remaining: localize system.leads ("Any") when a new item is created**
Do not merge as is

Localize Lifepath Sheet (unfinished)

---

lang/en.yml
module/constants.ts
templates/items/trait.hbs

Localize trait sheet

---

lang/en.yml
module/actors/sheets/BWCharacterSheet.ts
module/actors/sheets/NpcSheet.ts
module/items/item.ts
module/items/lifepath.ts
module/items/meleeWeapon.ts
module/items/rangedWeapon.ts
module/items/spell.ts
templates/items/lifepath.hbs
templates/items/rangedWeapon.hbs
templates/items/spell.hbs
templates/sections/header.hbs
types/Document.d.ts

Localize creation

---

lang/en.yml
module/burningwheel.ts
module/items/item.ts

Localize builtin foundry text

---

lang/en.yml
module/actors/BWCharacter.ts
module/actors/sheets/NpcSheet.ts
module/helpers.ts
module/macros/StatMacro.ts
module/rolls/fightRoll.ts
module/rolls/npcSkillRoll.ts
module/rolls/npcStatRoll.ts
module/rolls/rollArmor.ts
module/rolls/rollAttribute.ts
module/rolls/rollCircles.ts
module/rolls/rollLearning.ts
module/rolls/rollPtgs.ts
module/rolls/rollResources.ts
module/rolls/rollSkill.ts
module/rolls/rollSpellTax.ts
module/rolls/rollStat.ts
templates/chat/roll-message.hbs
templates/dialogs/roll-dialog.hbs
templates/parts/armor.hbs

Bw 474 localize test

---

templates/items/spell.hbs

Fix an issue with spell range inputs

---

lang/en.yml
module/actors/sheets/BWCharacterSheet.ts
module/dialogs/ImportItemDialog.ts
templates/dialogs/new-item-dialog.hbs

Bw 430 localize new item

---

lang/en.yml
module/actors/BWActor.ts
module/items/sheets/armor-sheet.ts
templates/items/armor.hbs

Resolves #489
Resolves #490
Resolves #491
Resolves #494

Multiple armor fixes

---

module/burningwheel.ts
module/rolls/customRolls.ts
module/rolls/rolls.ts
types/NumericTerm.d.ts
types/RollTerm.d.ts
types/StringTerm.d.ts
types/diceTerm.d.ts

Add shortcuts for system specific roll syntax

---

.circleci/config.yml
.gitattributes
.prettierrc.json
package.json
webpack.config.js

Fixes a number of issues with the build pipeline introduced because I'm a dingus.

Fix prettier line endings

---

lang/en.yml
module/actors/sheets/BWCharacterSheet.ts
module/burningwheel.ts
module/dialogs/ImportItemDialog.ts
module/helpers.ts
templates/sections/character-settings.hbs

v11 support

---

module/chat.ts
module/dialogs/burnerDataHelpers.ts
module/factory.ts
module/migration/task061.ts
package-lock.json
package.json
webpack.config.js

Fixed an issue where the new build pipeline was not properly showing eslint errors

Fix eslint errors being silenced

---

module/factory.ts

Fix an issue updating unlinked tokens

---

module/items/spell.ts

Resolves the issue opened up in #509

Only localize spell props if they are default

---

module/items/sheets/lifepath-sheet.ts

Fix an issue with drag and drop on lifepath

---

templates/items/skill.hbs
templates/parts/npc-stat.hbs

Hotifxes an issue where certain dropdowns (in skills and npcs) didn't keep their data properly.

Fix an issue where certain dropdowns didn't work

---

module/actors/BWActor.ts
module/actors/BWCharacter.ts
module/actors/sheets/BWSettingSheet.ts
module/burningwheel.ts
module/items/armor.ts
module/items/sheets/melee-sheet.ts
module/items/skill.ts
module/rolls/rerollFate.ts
module/rolls/rerollTraitors.ts
module/rolls/rollCircles.ts
module/rolls/rollLearning.ts
module/rolls/rollPtgs.ts
module/rolls/rollResources.ts
module/rolls/rollSkill.ts
module/rolls/rollSpell.ts
module/rolls/rolls.ts

Resolves #517 
(And a whole lot of other bugs)
Not super sure why these were still around but I'm sure I had good reason to keep them. :/

Refactor a number of legacy `data.` usages to `system.`

---

module/dialogs/CharacterBurnerDialog.ts

Changed data->system in the baseCharacterData actor update in the Character Burner.
Fixes [#520](https://github.com/StasTserk/foundry-burningwheel/issues/520#issue-2517867356)
-   [ ] Did this PR have to change `template.yml`?
-   [ ] If so, were there any steps taken to protect existing user data? A migration task?
-   [x] Did you follow the [contributing guidelines](https://github.com/StasTserk/foundry-burningwheel/blob/master/CONTRIBUTING.md)?
-   [x] Is this PR limited to fixing just one issue?

Data to System in character burner

---

module/rolls/npcSkillRoll.ts
module/rolls/rollWeapon.ts

Two small fixes
1. Fix localization of poor quality weapon
2. Apply poor quality weapon modifier to NPC rolls
Resolves #522
-   [ ] Did this PR have to change `template.yml`?
-   [ ] If so, were there any steps taken to protect existing user data? A migration task?
-   [x] Did you follow the [contributing guidelines](https://github.com/StasTserk/foundry-burningwheel/blob/master/CONTRIBUTING.md)?
-   [x] Is this PR limited to fixing just one issue?

Fix poor quality weapon rolls

---

.circleci/config.yml
tests/basicTests.spec.ts
tests/fixtures/baseFixture.ts
tests/fixtures/gameFixture.ts
tests/fixtures/index.ts
tests/fixtures/setupFixture.ts

Wraps the container setup in a timeout so it does not impact test running time
Resolves #538

Bw 538 test startup timer

---

lang/en.yml
module/items/lifepath.ts
module/items/rangedWeapon.ts
module/items/spell.ts

Fixes a number of bugs relating to localization getting applied when an item is first created.
Resolves #548

Fix a number of item creation localization errors

---

templates/sections/beliefs.hbs
templates/sections/instincts.hbs
tests/actors/character.spec.ts
tests/fixtures/parts/CharacterFixture.ts
tests/items/melee-weapon.spec.ts

Does some playwright testing of the character sheet
Relates to #531

Char sheet Tests Part 1

---

module/items/skill.ts
styles/character/weapons.scss
templates/chat/roll-message.hbs
templates/dialogs/roll-dialog.hbs
templates/parts/armor.hbs
templates/parts/relationships.hbs
templates/parts/rollable-item.hbs
templates/parts/weapons.hbs
tests/dialogs/roll-dialog.spec.ts
tests/fixtures/bwFixture.ts
tests/fixtures/gameFixture.ts
tests/fixtures/parts/CharacterFixture.ts
tests/fixtures/parts/ChatFixture.ts
tests/fixtures/parts/RelationshipFixture.ts
tests/fixtures/parts/RollDialog.ts

Testing roll functionality - Includes bugfix

---

templates/parts/rollable-item.hbs
templates/parts/rollable-skill.hbs

Adds a 5th difficult advancement tracking bubble if the skill/stat exponent is 9.
Resolves #557

Add 5th advancement circle of exponent is 9

---

module/rolls/rerollFate.ts

Fix beginner's luck fate reroll resetting stat fate

---

styles/dialog/difficulty.scss
styles/dialog/mods-and-help.scss

Fix z-index conflict between difficulty dialog and new document dialogs
Make difficulty dialog respect ui scale setting
Resolves #567

Bw 567 dialog UI issues
