- module/actor.ts
- module/rolls.ts
- module/rolls/rollAttribute.ts
- module/rolls/rollResources.ts
- styles/character/character.scss
- template.yml
- templates/character-sheet.html
- templates/chat/circles-dialog.html
- templates/chat/resources-dialog.html
Add option to use cash dice and funds in resources rolls.
Semi-automates tax (user prompts). Deducts from funds used first
Always removes cash dice used.
Changes cash and funds to be a number instead of a text entry field
in the character sheet.
Still missing support for fate re rolls to work correctly, but that whole setup melts my brain.
Resolves #34 - Resource roll automation
> Automate resource rolls

- module/actor.ts
- module/character-sheet.ts
- module/helpers.ts
- module/rolls/rerollCallon.ts
- module/rolls/rerollFate.ts
- module/rolls/rollSkill.ts
- module/templates.ts
- styles/burningwheel.scss
- styles/character/character.scss
- styles/character/settings.scss
- template.yml
- templates/character-sheet.html
- templates/parts/character-settings.html
Add a settings section that may be rendered at the top of the character
sheet that can be used to modify the way that certain values are
calculated and to manually edit any existing items attached to a
character
Resolves #56 - Sheet settings section
> Add sheet settings section

- module/character-sheet.ts
- module/items/item.ts
- module/items/sheets/instinct-sheet.ts
- templates/character-sheet.html
- templates/parts/rollable-item.html
Fixed an issue where custom1 and custom2 attribute labels were causing
duplicate ID issues with inputs when both were equal.
Fixed a few typos minor bugs
Resolves #31
> Fix duplicate ID errors with the two custom stats

- .circleci/config.yml
- module/burningwheel.ts
- module/character-sheet.ts
- module/migration.ts
- module/rolls/rerollCallon.ts
- module/rolls/rerollFate.ts
- module/rolls/rollAttribute.ts
- module/rolls/rollCircles.ts
- module/rolls/rollLearning.ts
- module/rolls/rollPtgs.ts
- module/rolls/rollResources.ts
- module/rolls/rollSkill.ts
- module/rolls/rollStat.ts
- module/rolls/rolls.ts
- module/settings.ts
Adds logic to character initialization that only adds initial items like fists and beliefs one time.
Adds code path for version based data migration.
Resolves #41
> Fix Duplicate fist weapon being added to a character sheet

- styles/character/character.scss
- templates/parts/rollable-skill.html
Skills shown in the character sheet now have a open ended roll toggle
just like stats and attributes.
Resolves #70 - Open skills toggle
> Add open ended toggle to skills partial

- module/actor.ts
- module/items/skill.ts
- module/rolls/rollLearning.ts
- module/rolls/rollSkill.ts
- module/rolls/rolls.ts
- styles/burningwheel.scss
- styles/items/item.scss
- styles/items/skill.scss
- styles/items/spell.scss
- template.yml
- templates/character-sheet.html
- templates/chat/roll-dialog.html
- templates/chat/skill-dialog.html
- templates/items/skill.html
Adds toolkit use flag to items.
Adds logic for applying the missing toolkit doubling penalty.
Adds logic for automatically rolling to expend an item marked as a toolkit.
Also refactors skill item sheet
Resolves #50
> Toolkit Penalty

- module/helpers.ts
- module/rolls/rollLearning.ts
- module/rolls/rolls.ts
- Fixed an issue where shade mismatch was not factoring into roots for
newly opened skills correctly.
- Fixed an issue where newly opened skill were not taking on the correct
shade of their parent skills
Resolves #62
> Fix issue with skill roots and shade

- module/rolls/rollLearning.ts
- module/rolls/rolls.ts
Learning a skill with multiple roots now has the player pick the root
they want to use ahead of time then preforms the roll based on that.
Resolves #87 - Fix Learning Roll Workflow
> Fix learning workflow

- module/burningwheel.ts
- module/character-sheet.ts
- module/dialogs/importItemDialog.ts
- styles/character/character.scss
- templates/character-sheet.hbs
- templates/dialogs/new-item-dialog.hbs
Adds a button to the new skill section that allows loading up the dialog
for importing skills.
Refactors other dialogs like this to use common code path.
Resolves #102
> Add "add new skill" button to skill list

- styles/burningwheel.scss
- styles/dialog/character-burner.scss
- styles/items/spell.scss
- styles/mixins.scss
- templates/dialogs/character-burner.hbs
- templates/items/affiliation.hbs
- templates/items/possession.hbs
- templates/items/property.hbs
- templates/items/rangedWeapon.hbs
- templates/items/relationship.hbs
- templates/items/reputation.hbs
- templates/items/skill.hbs
- templates/items/spell.hbs
Change checkboxes for toggles to be invisible, rather than hidden so
that they can be read by screen readers, be selected via keyboard, etc.
Resolves #117
> Update Checkbox Toggle styles

- module/burningwheel.ts
- module/dialogs/duel-of-wits.ts
Duel of wits no longer opens for all users whenever any data changes.
Duel of wits now properly registers listeners on initialization rather when first opened
Adds a new button in the duel of wits dialog to allow the GM to show the window to all players.
Resovles #141
> Duel of Wits fixes

- module/dialogs/fight.ts
Fixed a bug with clearing all fighters in the fight dialog leaving some
actors behind in the actor data cache.
Resolves #180
> Fix fight clear all bug

- module/character.ts
- styles/character/ptgs.scss
- template.yml
- templates/parts/ptgs.hbs
Adds 3 inputs to the PC sheet for recording partial recovery from
injuries. Numbers entered above the recovery notes subtract from the
wound dice directly.
Resolves #187
> Add ability to record wound recovery progress

- module/bwactor.ts
Fixed a bug where duplicating an actor was causing copies of the initial
items (beliefs, instincts, etc.) to be created again.
Also fixed an issue where creating a new character was causing an error
to be fired on all non-gm clients.
Resolves #189 - Actor Duplication
> Fix an issue with duplicate actor initialization

- module/rolls/fightRoll.ts
- module/rolls/npcSkillRoll.ts
- module/rolls/npcStatRoll.ts
- module/rolls/rerollCallon.ts
- module/rolls/rerollFate.ts
- module/rolls/rollLearning.ts
- module/rolls/rollSkill.ts
- module/rolls/rollStat.ts
- module/rolls/rolls.ts
- styles/chat/dialog.scss
- templates/chat/reroll-message.hbs
- templates/chat/roll-message.hbs
Resolves #184 - Enable split pool rerolls.
Rerolling with fate and call-ons will now correctly also reroll the secondary die pool.
In the case of open-ended skills, the fate point applies to only one of the pools at any given time.
> Split pool rerolls

- templates/dialogs/fight.hbs
Prevent the fight dialog from getting in a bad state if three actions
are scripted then the second action is unscripted -- disabled the
ability to unscript actions if there is already an action scripted after
in the same volley.
Resolves #197
> Prevent fight state issues

- module/bwactor-sheet.ts
The event handler for updating item inputs from an embedded character
sheet now properly ensure the right types of the data is stored
depending on input type.
Resolves #214
> Update type checking for item input updates

- module/dialogs/fight.ts
Fixed a problem where synchronizing actors between clients was causing
the order of those actors to appear in the backing actor data array to
change unexpectedly.
Resolves #216
> Fix an issue where actors in fight desynced

- module/dialogs/burnerDataHelpers.ts
- module/dialogs/characterBurner.ts
- module/items/sheets/skill-sheet.ts
- module/items/skill.ts
- module/rolls/rollLearning.ts
- templates/dialogs/character-burner.hbs
Allows skills to root their abilities off of emotional attributes.
Since those can be placed in either custom1 or custom2 attributes, these skills would have to specify which attribute they are based off of indirectly until they are added to the character sheet.
Resolves #230 - Orc skills rooted in hatred.
> Emotional skills

- module/dialogs/characterBurner.ts
- module/helpers.ts
- templates/dialogs/character-burner.hbs
The character burner now accepts items being dropped directly into it. It ensures they are cached correctly and the entries are populated.
> Character Burner accepting drops

- module/dialogs/CharacterBurnerDialog.ts
Fixed an issue where reputations and affiliations were using the wrong
resource point costs during character burning.
Also replaced all instances of `change` calls to `trigger("change")`.
Resolves #316
> Fix reputation and affiliation cost bug

- module/dialogs/CharacterBurnerDialog.ts
- module/items/lifepath.ts
- system.json
- template.yml
- templates/items/lifepath.hbs
Adds a negative stat toggle to the lifepath sheet which allows the lifepaths to subtract stats instead of adding them.
Resolves #318
> Negative stats from lifepaths

- .gitignore
- module/burningwheel.ts
- module/dialogs/FightDialog.ts
- module/rolls/fightRoll.ts
- styles/dialog/fight.scss
- templates/dialogs/fight.hbs
##Changes
This PR overhauls the look of Fight! dialog window. It optimises space and structures information, allowing for further Fight! additions like wounds, stance, tax, 1vX penatly, size Lock penalty ect..
Most notable changes are:
- combatants details(positon, engagement ect.) are now structured as a table
- combatants portraits are moved to overview
- hiding combatants for GM means overview shows only details, but not portrait or roll buttons
- Steel attribute roll is included to overview panel
- most HTML elements are now treated as flex to promote reactive design and look nicer on small resolutions/window sizes
- overview is able to show larger portraits for both GM and players
Possible TODOs: several fight tabs with Eye of the storm! feature, "sides" tag on actors, auto volley …
> Fight! style overhaul

- styles/character/bits.scss
- templates/character-sheet.hbs
I removed the colon from the Fate, Persona and Deeds checkboxes next to beliefs and instincts to reduce visual noise, aligned the checkbox to the line a little better and with the added space gave it all some breathing room. Finally I bolded the name of each row.
It's simple, but I hope it makes sense.
PS: Should now be in sync with the repo.
> Cleaner FPD (new)

- module/actors/BWActor.ts
- module/actors/BWCharacter.ts
- module/actors/Npc.ts
- module/actors/sheets/BWSettingSheet.ts
- module/factory.ts
- module/items/affiliation.ts
- module/items/armor.ts
- module/items/belief.ts
- module/items/instinct.ts
- module/items/lifepath.ts
- module/items/possession.ts
- module/items/property.ts
- module/items/rangedWeapon.ts
- module/items/relationship.ts
- module/items/reputation.ts
- module/items/sheets/affiliation-sheet.ts
- module/items/skill.ts
- module/items/spell.ts
- module/items/trait.ts
- module/migration/task063.ts
Fixes a number of issues noted in the 0.8.x upgrade pull request
Performs some cleanup on the types used for actors and items to keep
consistent use of generics.
Fixes an issue where the wrong item class was used for Affiliations in
the proxy class.
Resolves #340
> Type cleanup post 0.8.x upgrade

- .circleci/config.yml
- package-lock.json
Updates CircleCI node version
Does not jump to version 15 as that is not currently supported by gulp-sass.
> Update node version to 14.17.0

- module/actors/BWActor.ts
Removes use of getOwnedItems from _preCreate.
Relies on a bit of a bandaid fix due to missing types, but should be
the correct way to handle that process.
> Update _preCreate to not use deprecated behavior

- module/actors/sheets/BWCharacterSheet.ts
- module/actors/sheets/BWCharacterTabbedSheet.ts
- module/burningwheel.ts
- styles/character/character.scss
- templates/character-sheet.hbs
- templates/character-tabbed-sheet.hbs
Created a new character sheet template with tabs, that extends the default character sheet class.
Code changes structurally add tabs and re-arrange the contents of the sheet.
> Tabbed character sheet

- gulpfile.js
- module/dialogs/DifficultyDialog.ts
- package-lock.json
- package.json
Resolves #357 
Also includes a spot upgrade for gulp-sass, finally getting rid of the indirect dependency on the deprecated `node-sass`.
> Difficulty dialog events binding

- module/dialogs/DifficultyDialog.ts
- module/dialogs/ModifierDialog.ts
- module/dialogs/index.ts
- styles/dialog/difficulty.scss
- styles/dialog/mods-and-help.scss
- templates/dialogs/gm-difficulty.hbs
Allow the extended test overlay to be displayed even when the GM
difficulty dialog is disabled.
Resolves #368
> Allow extended test overlay without GM difficulty

- module/burningwheel.ts
- module/constants.ts
- module/dialogs/DuelOfWitsDialog.ts
- module/dialogs/FightDialog.ts
- module/dialogs/RangeAndCoverDialog.ts
- types/overrides.d.ts
Moves the extended test dialog action options to `constants.js`, adds them to the system for dialog import.
Also moves the dialog initialization to later in the initialization flow (on `ready` rather than on `init`) so a theoretical module may have time to modify said constants before they are loaded in as dialog options.
Resolves #400
> Move extended test dialog action options

- lang/en.yml
- templates/items/armor.hbs
- templates/items/meleeWeapon.hbs
- templates/items/possession.hbs
- templates/items/property.hbs
- Property sheet
- Small refactoring to remove duplicates for the key `bw.rpCost`
Resolves #440 
> Localize property sheet

- lang/en.yml
- templates/items/rangedWeapon.hbs
WIP on #441
- Static wording localized
- Remaining: localize system.maxRange on item creation to translate "paces"
> Localize ranged weapon sheet (unfinished)

- lang/en.yml
- module/constants.ts
- templates/items/spell.hbs
WIP on #445
`system.maxRange` and `system.description` still contain text to localize on item creation.
> Localize spell sheet

- lang/en.yml
- module/dialogs/CharacterBurnerDialog.ts
- module/items/lifepath.ts
- templates/items/lifepath.hbs
Adds functionality to provide the option of +2P lifepaths (needed for some Troll lifepaths), and also +2M (because once that's done anyone else who wants to add a +2M lifepath mirroring the +2P can).
I think I've added bits all the places they have mechanical effects...
Resolves hopefully, #379 
- [ x] Did this PR have to change `template.yml`?
- [ N/A] If so, were there any steps taken to protect existing user data? A migration task?
- [Y ] Did you follow the [contributing guidelines](https://github.com/StasTserk/foundry-burningwheel/blob/master/CONTRIBUTING.md)?
- [ Y] Is this PR limited to fixing just one issue?
> Extra attribute modifiers in lifepaths (Double Physical mod, Double Mental mod)

- templates/items/skill.hbs
Fixes an issue that was preventing some fields from appearing on an owned skill
Resolves #501
> Fix an hasOwner flag error in skill sheet

- module/actors/sheets/BWActorSheet.ts
- module/dialogs/ImportItemDialog.ts
- module/helpers.ts
Resolves #488 
Fixes an issue were items were being incorrectly duplicated when dragged from one actor to itself.
> Fix item duplication on drop

- module/dialogs/CharacterBurnerDialog.ts
Missed this one in the v12, but we can wait till the next release.
> Avoid using globalThis duplicate

- module/items/skill.ts
Shaded stats should reduce the Aptitude for all skills rooted from it by 1 for Gray shade, and by 2 for White shade. This is buried in the Heroic and Supernatural chapter (Burning Wheel Gold Revised, page 545).
Hesitation is calculated correctly, which is also reduced by the Will shade.
-   [ ] Did this PR have to change `template.yml`?
-   [ ] If so, were there any steps taken to protect existing user data? A migration task?
-   [x] Did you follow the [contributing guidelines](https://github.com/StasTserk/foundry-burningwheel/blob/master/CONTRIBUTING.md)?
-   [x] Is this PR limited to fixing just one issue?
> Fix shaded Stat aptitude

- .circleci/config.yml
- playwright.config.ts
Tries to fix the issue where test timings were not being properly accounted for in test splitting.
Also bumps parallelism up to 4 because why not.
> Use historical test timings from junit report.
